name: Deploy

on:
  push:
    branches:
      - production
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set Image Tag
        id: set_tag
        run: |
          # Set build date format
          BUILD_DATE=$(date +'%d-%m-%H-%M')

          # Determine the tag based on the branch
          if [ "${GITHUB_REF##*/}" == "production" ]; then
            IMAGE_TAG="production-${BUILD_DATE}"
          elif [ "${GITHUB_REF##*/}" == "development" ]; then
            IMAGE_TAG="development-${BUILD_DATE}"
          else
            echo "Unsupported branch: ${GITHUB_REF##*/}"
            exit 1
          fi

          echo "image_tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          
      - name: Build Docker image
        run: |
          docker-compose build
          docker tag ghcr.io/haihungnguyenn/cicd-handon/api:latest ghcr.io/haihungnguyenn/cicd-handon/api:${{ steps.set_tag.outputs.image_tag }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - env:
          IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
        run: |
          echo "********** $IMAGE_TAG"
          docker push ghcr.io/haihungnguyenn/cicd-handon/api:$IMAGE_TAG
